- hosts: localhost
  gather_facts: yes
  tasks:
  - name: Gathering service facts
    service_facts:
    register: services_state
  - debug: var=services_state.ansible_facts.services["jenkins.service"].state
  - debug: var=services_state.ansible_facts.services["firewalld.service"].state
